- name: kubectl apply dashboard
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

- name: copy manifests
  copy:
    src: "{{ role_path }}/files/manifests/"
    dest: "/home/ubuntu/manifests/"

- name: kubectl apply nginx-ingress-controller
  command: kubectl apply -f /home/ubuntu/manifests/nginx-ingress-controller.yaml

- name: kubectl apply admin-user for dashboard
  command: kubectl apply -f /home/ubuntu/manifests/admin-user.yaml

- name: copy syncconfig.yaml
  become: true
  copy:
   src: "{{ role_path }}/files/syncconfig.yaml"
   dest: "/etc/kubernetes/syncconfig.yaml"
